version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "12345:12345"
    networks:
      - mynetwork
    volumes:
      - ./server/config.ini:/app/config.ini  # Asegúrate de que la ruta en el contenedor sea la correcta

  client1:
    build: ./client
    environment:
      - CLIENT_ID=1
    depends_on:
      - server
    networks:
      - mynetwork
    volumes:
      - ./client/config.yaml:/app/config.yaml  # Asegúrate de que la ruta en el contenedor sea la correcta

networks:
  mynetwork:
    driver: bridge
